
#source code murni dari hasil latihan saya
#silakan bagi yang kurang puas di edit lagi sourcescode nya
#dan saya juga masih newbie di pemograman python

from getpass import getpass
import datetime
import time




status = False
i = 9000000000000000000000000000000000000000000000000000000000
daftar_password = [' andi','xxxx']

while i > 0:
	pwd = getpass(prompt="masukan password anda:")
	pwd2 = getpass(prompt = "masukan password kembali:")
	for password in daftar_password:
		if pwd ==password:
			print "password benar"
			status = True
			break
	if not status:	
		print "password salah"
		i = i - 1
		continue
	else:
		break	
#intruksi untuk kembali 
print'''

                                                                                                            _____                   
_______    ______                _____ ___________         _____               _____  ______   _______   _____\    \___________       
\      |  |      |          _____\    \\          \      /      |_        _____\    \|\     \  \      \ /    / |    \          \      
 |     /  /     /|         /     /|     \    /\    \    /         \      /     /|     \\     \  |     //    /  /___/|\    /\    \     
 |\    \  \    |/         /     / /____/||   \_\    |  |     /\    \    /     / /____/|\|     |/     //    |__ |___|/ |   \_\    |    
 \ \    \ |    |         |     | |____|/ |      ___/   |    |  |    \  |     | |____|/  |     |_____//|       \       |      ___/     
  \|     \|    |         |     |  _____  |      \  ____|     \/      \ |     |  _____   |     |\     \|     __/ __    |      \  ____  
   |\         /|         |\     \|\    \/     /\ \/    \\      /\     \|\     \|\    \ /     /|\|     |\    \  /  \  /     /\ \/    \ 
   | \_______/ |         | \_____\|    /_____/ |\______| \_____\ \_____\ \_____\|    |/_____/ |/_____/| \____\/    |/_____/ |\______| 
    \ |     | /          | |     /____/|     | | |     | |     | |     | |     /____/|     | / |    | | |    |____/||     | | |     | 
     \|_____|/            \|_____|    ||_____|/ \|_____|\|_____|\|_____|\|_____|    ||_____|/  |____|/ \|____|   | ||_____|/ \|_____| 
                                 |____|/                                       |____|/                       |___|/                   
	'''
print '\n'

print 				'selamat datang di program saya ==by andi ahmad saputra'
print 				   'program ini berguna untuk pembuatan wordlist'
print 				'berguna untuk crack password dengan metode bruteforce'
print 				   'masukan perkata--kata-kata yang anda pikirkan'
print 				    'maka program akan mengacak kata tersebut'
	
print '\n'

keputusan = 'y'
while (keputusan !='n'):
	nama_file = raw_input('masukan nama file:')
	word = open(nama_file,'a+')
	
	print '\n'
	a = raw_input("kata_1:")
	b = raw_input("kata_2:")
	c = raw_input("kata_3:")
	d = raw_input("kata_4:")
	e = raw_input("kata_5:")
	f = raw_input("kata_6:")
	g = raw_input("kata_7:")
	h = raw_input("kata_8:")
	i = raw_input("kata_9:")
	j = raw_input("kata_10:")
	k = raw_input("kata_11:")
	l = raw_input("kata_12:")
	m  = raw_input("kata_13:")
	n  = raw_input("kata_14:")
	o  = raw_input("kata_15:")
	

	print '\n'
	word.write(a)
	word.write('\n')
	word.write(b)
	word.write('\n')
	word.write(c)
	word.write('\n')
	word.write(d)
	word.write('\n')
	word.write(e)
	word.write('\n')
	word.write(f)
	word.write('\n')
	word.write(g)
	word.write('\n')
	word.write(h)
	word.write('\n')
	word.write(i)
	word.write('\n')
	word.write(j)
	word.write('\n')
	word.write(k)
	word.write('\n')
	word.write(l)
	word.write('\n')
	word.write(m)
	word.write('\n')
	word.write(n)
	word.write('\n')
	word.write(o)
	word.write('\n')
	word.write(a + b)
	word.write('\n')
	word.write(a + c)
	word.write('\n')
	word.write(a + d)
	word.write('\n')
	word.write(a + e)
	word.write('\n')
	word.write(a + f)
	word.write('\n')
	word.write(a + g)
	word.write('\n')
	word.write(a + h)
	word.write('\n')
	word.write(a + i)
	word.write('\n')
	word.write(a + j)
	word.write('\n')
	word.write(a + k)
	word.write('\n')
	word.write(a + l)
	word.write('\n')
	word.write(a + m)
	word.write('\n')
	word.write(a + n)
	word.write('\n')
	word.write(a + o)
	word.write('\n')
#kebalikan dari a
	word.write(b + a)
	word.write('\n')
	word.write(c + a)
	word.write('\n')
	word.write(d + a)
	word.write('\n')
	word.write(e + a)
	word.write('\n')
	word.write(f + a)
	word.write('\n')
	word.write(g + a)
	word.write('\n')
	word.write(h + a)
	word.write('\n')
	word.write(i + a)
	word.write('\n')
	word.write(j + a)
	word.write('\n')
	word.write(k + a)
	word.write('\n')
	word.write(l + a)
	word.write('\n')
	word.write(m + a)
	word.write('\n')
	word.write(n + a)
	word.write('\n')
	word.write(m + a)
	word.write('\n')
	word.write(o + a)
	word.write('\n')
	
#obeject baru b
	word.write(b + c)
	word.write('\n')
	word.write(b + d)
	word.write('\n')
	word.write(b + e)
	word.write('\n')
	word.write(b + f)
	word.write('\n')
	word.write(b + g)
	word.write('\n')
	word.write(b + h)
	word.write('\n')
	word.write(b + i)
	word.write('\n')
	word.write(b + j)
	word.write('\n')
	word.write(b + k)
	word.write('\n')
	word.write(b + l)
	word.write('\n')
	word.write(b + m)
	word.write('\n')
	word.write(b + n)
	word.write('\n')
	word.write(b + m)
	word.write('\n')
	word.write(b + o)
	word.write('\n')
#kebalikan dari b
	word.write(c + b)
	word.write('\n')
	word.write(d + b)
	word.write('\n')
	word.write(e + b)
	word.write('\n')
	word.write(f + b)
	word.write('\n')
	word.write(g + b)
	word.write('\n')
	word.write(h + b)
	word.write('\n')
	word.write(i + b)
	word.write('\n')
	word.write(j + b)
	word.write('\n')
	word.write(k + b)
	word.write('\n')
	word.write(l + b)
	word.write('\n')
	word.write(m + b)
	word.write('\n')
	word.write(n + b)
	word.write('\n')
	word.write(o + b)
	word.write('\n')
	#object baru dari c
	word.write(c + d)
	word.write('\n')
	word.write(c + e)
	word.write('\n')
	word.write(c + f)
	word.write('\n')
	word.write(c + g)
	word.write('\n')
	word.write(c + h)
	word.write('\n')
	word.write(c + i)
	word.write('\n')
	word.write(c + j)
	word.write('\n')
	word.write(c + k)
	word.write('\n')
	word.write(c + l)
	word.write('\n')
	word.write(c + m)
	word.write('\n')
	word.write(c + n)
	word.write('\n')
	word.write(c + o)
	word.write('\n')
	#kebalikan dari c
	word.write(d + c)
	word.write('\n')
	word.write(e + c)
	word.write('\n')
	word.write(f + c)
	word.write('\n')
	word.write(g + c)
	word.write('\n')
	word.write(h + c)
	word.write('\n')
	word.write(i + c)
	word.write('\n')
	word.write(j + c)
	word.write('\n')
	word.write(k + c)
	word.write('\n')
	word.write(l + c)
	word.write('\n')
	word.write(m + c)
	word.write('\n')
	word.write(n + c)
	word.write('\n')
	word.write(o + c)
	word.write('\n')
	#object baru dari d
	word.write(d + e)
	word.write('\n')
	word.write(d + f)
	word.write('\n')
	word.write(d + g)
	word.write('\n')
	word.write(d + h)
	word.write('\n')
	word.write(d + i)
	word.write('\n')
	word.write(d + j)
	word.write('\n')
	word.write(d + k)
	word.write('\n')
	word.write(d + l)
	word.write('\n')
	word.write(d + m)
	word.write('\n')
	word.write(d + n)
	word.write('\n')
	word.write(d + o)
	word.write('\n')
	#kebalikan dari d
	word.write(e + d)
	word.write('\n')
	word.write(f + d)
	word.write('\n')
	word.write(g + d)
	word.write('\n')
	word.write(h + d)
	word.write('\n')
	word.write(i + d)
	word.write('\n')
	word.write(j + d)
	word.write('\n')
	word.write(k + d)
	word.write('\n')
	word.write(l + d)
	word.write('\n')
	word.write(m + d)
	word.write('\n')
	word.write(n + d)
	word.write('\n')
	word.write(o + d)
	#object baru dari e
	word.write(e + f)
	word.write('\n')
	word.write(e + g)
	word.write('\n')
	word.write(e + h)
	word.write('\n')
	word.write(e + i)
	word.write('\n')
	word.write(e + j)
	word.write('\n')
	word.write(e + k)
	word.write('\n')
	word.write(e + l)
	word.write('\n')
	word.write(e + m)
	word.write('\n')
	word.write(e + n)
	word.write('\n')
	word.write(e + o)
	word.write('\n')
	#kebalikan dari e
	word.write(f + e)
	word.write('\n')
	word.write(g + e)
	word.write('\n')
	word.write(h + e)
	word.write('\n')
	word.write(i + e)
	word.write('\n')
	word.write(j + e)
	word.write('\n')
	word.write(k + e)
	word.write('\n')
	word.write(l + e)
	word.write('\n')
	word.write(m + e)
	word.write('\n')
	word.write(n + e)
	word.write('\n')
	word.write(o + e)
	word.write('\n')
	#object baru dari f
	word.write(f + g)
	word.write('\n')
	word.write(f + h)
	word.write('\n')
	word.write(f + i)
	word.write('\n')
	word.write(f + j)
	word.write('\n')
	word.write(f + k)
	word.write('\n')
	word.write(f + l)
	word.write('\n')
	word.write(f + m)
	word.write('\n')
	word.write(f + n)
	word.write('\n')
	word.write(f + o)
	word.write('\n')
	#kebalikan dari f
	word.write(g + f)
	word.write('\n')
	word.write(h + f)
	word.write('\n')
	word.write(i + f)
	word.write('\n')
	word.write(j + f)
	word.write('\n')
	word.write(k + f)
	word.write('\n')
	word.write(l + f)
	word.write('\n')
	word.write(m + f)
	word.write('\n')
	word.write(n + f)
	word.write('\n')
	word.write(o + f)
	word.write('\n')
	#objek baru dari g
	word.write(g + h)
	word.write('\n')
	word.write(g + i)
	word.write('\n')
	word.write(g + j)
	word.write('\n')
	word.write(g + k)
	word.write('\n')
	word.write(g + l)
	word.write('\n')
	word.write(g + m)
	word.write('\n')
	word.write(g + n)
	word.write('\n')
	word.write(g + o)
	word.write('\n')
	#kebalikan dari g
	word.write(h + g)
	word.write('\n')
	word.write(i + g)
	word.write('\n')
	word.write(j + g)
	word.write('\n')
	word.write(k + g)
	word.write('\n')
	word.write(l + g)
	word.write('\n')
	word.write(n + g)
	word.write('\n')
	word.write(m + g)
	word.write('\n')
	word.write(n + g)
	word.write('\n')
	word.write(o + g)
	word.write('\n')
	#objek baru h
	word.write(h + i)
	word.write('\n')
	word.write(h + j)
	word.write('\n')
	word.write(h + k)
	word.write('\n')
	word.write(h + l)
	word.write('\n')
	word.write(h + m)
	word.write('\n')
	word.write(h + n)
	word.write('\n')
	word.write(h + o)
	word.write('\n')
	#kebalikan dari h
	word.write(i + h)
	word.write('\n')
	word.write(j + h)
	word.write('\n')
	word.write(k + h)
	word.write('\n')
	word.write(l + h)
	word.write('\n')
	word.write(m + h)
	word.write('\n')
	word.write(n + h)
	word.write('\n')
	word.write(o + h)
	#objek baru i
	word.write(i + j)
	word.write('\n')
	word.write(i + k)
	word.write('\n')
	word.write(i + l)
	word.write('\n')
	word.write(i + m)
	word.write('\n')
	word.write(i + n)
	word.write('\n')
	word.write(i + o)
	word.write('\n')
	#kebalikan i
	word.write(j + i)
	word.write('\n')
	word.write(k + i)
	word.write('\n')
	word.write(l + i)
	word.write('\n')
	word.write(m + i)
	word.write('\n')
	word.write(n + i)
	word.write('\n')
	word.write(o + i)
	word.write('\n')

	#baru j
	word.write(j + k)
	word.write('\n')
	word.write(j + l)
	word.write('\n')
	word.write(j + m)
	word.write('\n')
	word.write(j + n)
	word.write('\n')
	word.write(j + o)
	word.write('\n')

	#kebalikan j
	word.write(k + j)
	word.write('\n')
	word.write(l + j)
	word.write('\n')
	word.write(m + j)
	word.write('\n')
	word.write(n + j)
	word.write('\n')
	word.write(o + j)
	word.write('\n')

	#baru k
	word.write(k + l)
	word.write('\n')
	word.write(k + m)
	word.write('\n')
	word.write(k + n)
	word.write('\n')
	word.write(k + o)
	word.write('\n')
	
	#kebalikan k
	word.write(l + k)
	word.write('\n')
	word.write(m + k)
	word.write('\n')
	word.write(n + k)
	word.write('\n')
	word.write(o + k)
	word.write('\n')

	#baru l
	word.write(l + m)
	word.write('\n')
	word.write(l + n)
	word.write('\n')
	word.write(l + o)
	word.write('\n')

	#kebalikan l
	word.write(m + l)
	word.write('\n')
	word.write(n + l)
	word.write('\n')
	word.write(o + l)
	word.write('\n')

	#baru m
	word.write(m + n)
	word.write('\n')
	word.write(m + o)
	word.write('\n')

	#kebalikan m
	word.write(n + m)
	word.write('\n')
	word.write(o + m)
	word.write('\n')

	#baru n
	word.write(n + o)
	word.write('\n')

	#kebalikan n
	word.write(o + n)
	word.write('\n')

	
	 

	print '\n'
	keputusan = raw_input("anda ingin melanjutkan[y/n]:")
	if keputusan == 'n':
		print "selamat membobol"
					
	





